# Bun configuration file
# See https://bun.sh/docs/runtime/bunfig for more options

[install]
# Configure package installation
cache = true
exact = false
frozen = false
production = false

# Registry configuration
registry = "https://registry.npmjs.org"

[install.scopes]
# Scoped package registries can be configured here

[run]
# Runtime configuration
bun = true

[test]
# Test runner configuration
preload = [] 